server:
  port: 8080

spring:
  application:
    name: bookstore-api
  
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin123

# JWT Configuration
jwt:
  secret: rikiBookstoreSecretKey2024ForJWTTokenGeneration
  expiration: 86400000 # 24 hours in milliseconds

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging
logging:
  level:
    com.riki: DEBUG
    org.springframework.security: DEBUG
